name: larkfinserv_flutter
description: A Flutter SDK for integrating Lark FinServ's loan eligibility check functionality into your Flutter applications.
version: 1.0.0
homepage: https://github.com/yourusername/larkfinserv_flutter
repository: https://github.com/yourusername/larkfinserv_flutter.git
issue_tracker: https://github.com/yourusername/larkfinserv_flutter/issues

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.13.0
  url_launcher: ^6.3.2
  http: ^1.5.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
